name: subductionPCA
dependencies:
  - python=3.10
  - numpy=1.23.3
  - matplotlib=3.5.3
  - scipy=1.9.3
  - pandas=2.2.1
  - conda-forge::pendulum=2.1.2
  - conda-forge::nbdime=3.2.1
  - conda-forge::jupytext=1.15.2
  - notebook=6.5
  - jupyterlab=3.6 
  - pip=23.2.1
  - pip:
     - -r requirements.txt